// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clearDB.sql

package database

import (
	"context"
)

const clearDB = `-- name: ClearDB :exec
TRUNCATE users, feeds, feed_follows
`

func (q *Queries) ClearDB(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDB)
	return err
}
