// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feedByURL.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id
FROM feeds
WHERE url = $1
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
