// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: listFeeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const listFeeds = `-- name: ListFeeds :many
SELECT name, url, user_id
FROM feeds
`

type ListFeedsRow struct {
	Name   string
	Url    string
	UserID uuid.UUID
}

func (q *Queries) ListFeeds(ctx context.Context) ([]ListFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedsRow
	for rows.Next() {
		var i ListFeedsRow
		if err := rows.Scan(&i.Name, &i.Url, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
